### ISSUE TITLE
Open source usage of this Theme?

### ISSUE THREAD

**Issue by adamar** [themefisher/Blue-Onepage-HTML5-Business-Template#1]
Hi,

I've created a simple payment page that connects to Stripe and I've used this theme to make it look a bit prettier. I was hoping to check with you and make sure your fine with what I've done, as I'm not exactly sure how it fits with the License file you included?

-Adamar

**Comment by themefisher** [comment]
Hello,
Thanks for choosing my template for your purpose. You can use my template totally free.But you dont have that right to remove the footer credit . if you donate only then you can remove the credit .for more info contact with me through themefisher@gmail.com/
Thanks
